config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: 'new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  post 'tasks/:id', to: 'tasks#update'

  post 'tasks/:id/dotask', to: 'tasks#dotask', as: 'dotask'

  delete 'tasks/:id', to: 'tasks#destroy'

  get 'tasks/:id', to: 'tasks#show', as: 'task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def dotask
    @task = Task.find(params[:id])
    @task.completed = true
    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script type="text/javascript">
      console.log('hey');
      const tasks = document.querySelectorAll(".task");
      const row = `<p>hello</p>`;
      tasks.forEach((task) => {
        task.addEventListener("click", (event) => {
          event.insertAdjacentHTML("beforeend", row);
        });
      });
    </script>
  </body>

</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<form action="/tasks/<%= @task.id %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Title: </label>
  <input type="text" name="task[title]" id="title" value= "<%= @task.title %>">

  <label for="details">Details: </label>
  <input type="textarea" name="task[details]" id="details" value= "<%= @task.details %>">

  <input type="submit" value="Edit Task">

</form>

app/views/tasks/index.html.erb
<div class="col col-xs-12 col-sm-6 col-md-4">

  <div class="title">
    <h1>my tasks list</h1>
  </div>
  <div class="add-task">
    <%= link_to '+', new_path %>
  </div>
    <% @tasks.each do |task| %>
      <div class="task">
        <% if task.completed %>
          <input type="checkbox" id="<% task.id %>" name="<% task.id %>" checked>
          <label class="task-title-done" for="<% task.id %>"><%= link_to task.title, task_path(task) %></label>
        <% else %>
          <%= link_to dotask_path(task), method: :post do %>
            <input id="box1" type="checkbox" />
          <% end %>
          <label for="box1"><%= link_to task.title, task_path(task) %></label>
        <% end  %>
        <%= link_to raw('<i class="fa fa-eraser" aria-hidden="true"></i>'), task_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>



</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Title: </label>
  <input type="text" name="task[title]" id="title">

  <label for="details">Details: </label>
  <input type="textarea" name="task[details]" id="details">

  <input type="submit" value="New Task">

</form>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>
<div>
  <input type="checkbox" id="<% @task.id %>" name="<% @task.id %>" <%= 'checked' if @task.completed %>>
  <label for="<% @task.id %>"><%= @task.completed ? 'this task is completed' : "this task is not yet completed" %></label>
</div>

<%= link_to 'edit my task', edit_path(@task) %>
<%= link_to 'back to the list', tasks_path %>